name: Build on release

on: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup: Checkout"
        uses: actions/checkout@v2
      - name: "Setup: Python 3.8"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: "Setup: Dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install ttfautohint
          sudo snap install yq
      - name: "Setup: Cache"
        uses: actions/cache@v2
        with:
          path: ./venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - name: "Setup: Zip file name"
        id: zip-name
        shell: bash
        run: echo "ZIP_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')-fonts" >> $GITHUB_ENV
      - name: Build font
        run: make build
      - name: Check font -- Font Bakery
        run: make test
        continue-on-error: true
      - name: Check font -- Make proof
        run: make proof
      - name: Check font -- Generate site
        run: cp scripts/index.html out/index.html
      - name: Deploy -- Archive
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ZIP_NAME }}
          path: |
            fonts
            out
    outputs:
      zip_name: ${{ env.ZIP_NAME }}
